### ISSUE TITLE
method "camelize" not found during "piston update" (ActiveSupport 3.0.0 incompat?)

### ISSUE THREAD

**Issue by chillu** [francois/piston#7] opened 2010-09-14 04:16 UTC
This happens on a "piston update" call on a local git repo.

I've encountered this when switching from the built-in ruby/gem installation in OS X
to MacPorts, but suspect that the actual cause is an update of the "rails" gem
(which in turn updates the "activesupport" gem). 

Doing `gem uninstall activesupport -v 3.0.0` did the trick (downgrading to `2.3.5`) it seems.

I can't find any specific references that `camelize()` has been removed from ActiveSupport,
maybe I'm just going nuts?

Stacktrace:

```
/Library/Ruby/Gems/1.8/gems/piston-2.0.9/lib/piston/cli.rb:66:in `start': undefined method `camelize' for "update":String (NoMethodError)
        from /Library/Ruby/Gems/1.8/gems/piston-2.0.9/lib/piston/cli.rb:121
        from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
        from /Library/Ruby/Gems/1.8/gems/piston-2.0.9/bin/piston:5
        from /usr/bin/piston:19:in `load'
        from /usr/bin/piston:19
```

Environment:
- OS X 10.6
- ruby 1.8.7 and gem 1.3.7 through MacPorts
- rails, activesupport, etc 3.0.0 (through MacPorts gem)

**Comment by francois** [comment] 2010-09-14 12:14
Don't accept ActiveSupport 3.0

Apparently, #7 was caused by ActiveSupport 3.0. Closed by 6f436edc5570ea0e32899801f25e2b7d2c11ca4e.

**Closed as completed by francois** 2010-09-14 12:14 UTC
